import 'package:supabase_flutter/supabase_flutter.dart';
import '../../domain/models/order.dart';

abstract class OrdersRepository {
  Future<List<Order>> getAll();
  Future<Order> getByTrackingCode(String code);
  Future<Order> create(Order order);
  Future<Order> update(String id, Map<String, dynamic> data);
  Future<void> delete(String id);
  Stream<List<Order>> watchAll();
}

class SupabaseOrdersRepository implements OrdersRepository {
  final SupabaseClient _client;
  SupabaseOrdersRepository(this._client);

  @override
  Future<List<Order>> getAll() async {
    final data = await _client
        .from('orders')
        .select()
        .order('created_at', ascending: false);
    return (data as List).map((e) => Order.fromJson(e)).toList();
  }

  @override
  Future<Order> getByTrackingCode(String code) async {
    final data = await _client
        .from('orders')
        .select()
        .eq('tracking_code', code)
        .single();
    return Order.fromJson(data);
  }

  @override
  Future<Order> create(Order order) async {
    final orderData = order.toJson();
    
    // Remove fields that should be generated by Supabase
    orderData.remove('id');
    orderData.remove('tracking_code');
    orderData.remove('created_at');
    orderData.remove('updated_at');
    
    // Ensure tech_id is null if not provided, not an empty string
    if (orderData['tech_id'] == null || orderData['tech_id'].toString().isEmpty) {
      orderData.remove('tech_id');
    }

    final data = await _client
        .from('orders')
        .insert(orderData)
        .select()
        .single();
    return Order.fromJson(data);
  }

  @override
  Future<Order> update(String id, Map<String, dynamic> data) async {
    final response = await _client
        .from('orders')
        .update(data)
        .eq('id', id)
        .select()
        .single();
    return Order.fromJson(response);
  }

  @override
  Future<void> delete(String id) async {
    await _client.from('orders').delete().eq('id', id);
  }

  @override
  Stream<List<Order>> watchAll() {
    return _client
        .from('orders')
        .stream(primaryKey: ['id'])
        .order('created_at', ascending: false)
        .map((data) => data.map((e) => Order.fromJson(e)).toList());
  }
}
